services:
    kedb:
        container_name: divisitor
        image: repo.indonesian-aerospace.com/dev-apps/divisitor
        volumes:
            - ./:/var/www/divisitor
        ports:
            - "8000:80"
        extra_hosts:
            - "sso-dev:10.1.94.149"
            - "helpdesk-api-dev:10.1.95.38"
            - "host.docker.internal:host-gateway"
        environment:
            # laravel specific environment
            - APP_NAME=di-visitors
            - APP_ENV=local
            - APP_KEY=base64:rsUMrarsrxtEs24n16j36UhkdTpBapkQ7v6dPAQSSac=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            # keycloak configuration
            - KEYCLOAK_BASE_URL=https://sso-dev.indonesian-aerospace.com
            - KEYCLOAK_REALM=dev
            - KEYCLOAK_CLIENT_ID=divisitor
            - KEYCLOAK_REDIRECT_URL=http://localhost:8000
            # database connection
            - DB_CONNECTION=pgsql
            - DB_HOST=10.1.94.149
            - DB_PORT=5552
            - DB_DATABASE=dbvms
            - DB_USERNAME=uvms
            - DB_PASSWORD=uvms2024
            # another
            - APP_PROTOCOL=http
            - INFO_API=http://helpdesk-api-dev
            - PHOTO_API=http://portal.indonesian-aerospace.com/data/foto
